# Generated by Django 4.2.6 on 2023-10-14 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(default='https://i0.wp.com/blankhans.io/wp-content/uploads/2021/08/placeholder.png?fit=1200%2C800&ssl=1', max_length=500)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('lenght', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('publishing_date', models.DateField(null=True)),
                ('author', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_history', models.ManyToManyField(related_name='purchase_history', to='store_api.product')),
                ('wishlist', models.ManyToManyField(related_name='wishlist', to='store_api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='store_api.tag'),
        ),
    ]
