# Generated by Django 4.2.6 on 2023-11-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_alter_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store_api.productreviewhistory'),
        ),
    ]
