# Generated by Django 4.2.6 on 2023-10-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_alter_product_author_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
