# Generated by Django 4.2.6 on 2023-10-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0007_pendingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_ordering', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='products', to='store_api.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='purchase_history',
        ),
        migrations.DeleteModel(
            name='PendingOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store_api.profile'),
        ),
    ]
